### ISSUE TITLE
[Feat] 베팅 API 수정 사항 적용

### ISSUE THREAD

**Issue by Cutaku** [Do-it-Together-DoTo/DoTo_Back#135]
# Description
> 베팅 API 수정 사항 적용

# Todo
- [ ] Member entity 수정에 따른 query문 수정
- [ ] 비공개 된 카테고리에서는 베팅 생성 안되도록 수정
- [ ] 베팅 참여 시 Record 기록 업데이트
- [ ] 친구의 베팅만 조회 가능하도록 수정
