### ISSUE TITLE
[Feat] Category Mock API 구현

### ISSUE THREAD

**Issue by Cutaku** [Do-it-Together-DoTo/DoTo_Back#32]
# Description
> 카테고리 관련 Mock API 구현

# Todo
- [x] API 별 DTO 생성
- [x] 카테고리 생성
- [x] 카테고리 전체 조회
- [x] 카테고리 수정
- [x] 카테고리 삭제
- [x] 카테고리 순서 변경
