### ISSUE TITLE
[Feat] 엔티티 조회 메소드 구현

### ISSUE THREAD

**Issue by Cutaku** [Do-it-Together-DoTo/DoTo_Back#63]
# Description
> 엔티티 조회 메소드 구현

# Todo
- [x] 투두 조회 메소드 구현
- [x] 베팅 조회 메소드 구현
- [x] 캐릭터 조회 메소드 구현
- [x] 캐릭터 종류 조회 메소드 구현
- [x] 아이템 종류 조회 메소드 구현
- [x] 채팅방 조회 메소드 구현
