### ISSUE TITLE
[Feat] Redis 설정 추가 및 Record 에 redis 적용

### ISSUE THREAD

**Issue by Cutaku** [Do-it-Together-DoTo/DoTo_Back#80]
# Description
> Redis 설정 추가 및 Record 에 redis 적용

# Todo
- [x] redis 설정 추가
- [x] Record 에 redis 적용
- [x] 베팅 api에 Record 기록 반영
